pokemons = [
    # Generación 1
    {"numero": 1, "nombre": "Bulbasaur", "tipos": ["Planta", "Veneno"], "debilidades": ["Fuego", "Psíquico", "Volador", "Hielo"], "mega_evolucion": False, "gigamax": False},
    {"numero": 3, "nombre": "Venusaur", "tipos": ["Planta", "Veneno"], "debilidades": ["Fuego", "Psíquico", "Volador", "Hielo"], "mega_evolucion": True, "gigamax": True},
    {"numero": 6, "nombre": "Charizard", "tipos": ["Fuego", "Volador"], "debilidades": ["Agua", "Eléctrico", "Roca"], "mega_evolucion": True, "gigamax": True},
    {"numero": 9, "nombre": "Blastoise", "tipos": ["Agua"], "debilidades": ["Planta", "Eléctrico"], "mega_evolucion": True, "gigamax": True},
    {"numero": 25, "nombre": "Pikachu", "tipos": ["Eléctrico"], "debilidades": ["Tierra"], "mega_evolucion": False, "gigamax": True},
    {"numero": 26, "nombre": "Raichu", "tipos": ["Eléctrico"], "debilidades": ["Tierra"], "mega_evolucion": False, "gigamax": False},
    {"numero": 39, "nombre": "Jigglypuff", "tipos": ["Normal", "Hada"], "debilidades": ["Veneno", "Acero"], "mega_evolucion": False, "gigamax": False},
    {"numero": 65, "nombre": "Alakazam", "tipos": ["Psíquico"], "debilidades": ["Bicho", "Fantasma", "Siniestro"], "mega_evolucion": True, "gigamax": False},
    {"numero": 68, "nombre": "Machamp", "tipos": ["Lucha"], "debilidades": ["Volador", "Psíquico", "Hada"], "mega_evolucion": False, "gigamax": True},
    {"numero": 94, "nombre": "Gengar", "tipos": ["Fantasma", "Veneno"], "debilidades": ["Psíquico", "Fantasma", "Siniestro", "Tierra"], "mega_evolucion": True, "gigamax": True},
    {"numero": 131, "nombre": "Lapras", "tipos": ["Agua", "Hielo"], "debilidades": ["Planta", "Eléctrico", "Lucha", "Roca"], "mega_evolucion": False, "gigamax": True},
    {"numero": 133, "nombre": "Eevee", "tipos": ["Normal"], "debilidades": ["Lucha"], "mega_evolucion": False, "gigamax": True},
    {"numero": 143, "nombre": "Snorlax", "tipos": ["Normal"], "debilidades": ["Lucha"], "mega_evolucion": False, "gigamax": True},
    {"numero": 150, "nombre": "Mewtwo", "tipos": ["Psíquico"], "debilidades": ["Bicho", "Fantasma", "Siniestro"], "mega_evolucion": True, "gigamax": False},
    
    # Generación 2
    {"numero": 154, "nombre": "Meganium", "tipos": ["Planta"], "debilidades": ["Fuego", "Hielo", "Veneno", "Volador", "Bicho"], "mega_evolucion": False, "gigamax": False},
    {"numero": 157, "nombre": "Typhlosion", "tipos": ["Fuego"], "debilidades": ["Agua", "Tierra", "Roca"], "mega_evolucion": False, "gigamax": False},
    {"numero": 160, "nombre": "Feraligatr", "tipos": ["Agua"], "debilidades": ["Planta", "Eléctrico"], "mega_evolucion": False, "gigamax": False},
    {"numero": 181, "nombre": "Ampharos", "tipos": ["Eléctrico"], "debilidades": ["Tierra"], "mega_evolucion": True, "gigamax": False},
    {"numero": 196, "nombre": "Espeon", "tipos": ["Psíquico"], "debilidades": ["Bicho", "Fantasma", "Siniestro"], "mega_evolucion": False, "gigamax": False},
    {"numero": 197, "nombre": "Umbreon", "tipos": ["Siniestro"], "debilidades": ["Lucha", "Bicho", "Hada"], "mega_evolucion": False, "gigamax": False},
    {"numero": 212, "nombre": "Scizor", "tipos": ["Bicho", "Acero"], "debilidades": ["Fuego"], "mega_evolucion": True, "gigamax": False},
    {"numero": 248, "nombre": "Tyranitar", "tipos": ["Roca", "Siniestro"], "debilidades": ["Lucha", "Tierra", "Bicho", "Acero", "Agua", "Planta", "Hada"], "mega_evolucion": True, "gigamax": False},
    
    # Generación 3
    {"numero": 254, "nombre": "Sceptile", "tipos": ["Planta"], "debilidades": ["Fuego", "Hielo", "Veneno", "Volador", "Bicho"], "mega_evolucion": True, "gigamax": False},
    {"numero": 257, "nombre": "Blaziken", "tipos": ["Fuego", "Lucha"], "debilidades": ["Agua", "Psíquico", "Volador", "Tierra"], "mega_evolucion": True, "gigamax": False},
    {"numero": 260, "nombre": "Swampert", "tipos": ["Agua", "Tierra"], "debilidades": ["Planta"], "mega_evolucion": True, "gigamax": False},
    {"numero": 282, "nombre": "Gardevoir", "tipos": ["Psíquico", "Hada"], "debilidades": ["Veneno", "Fantasma", "Acero"], "mega_evolucion": True, "gigamax": False},
    {"numero": 302, "nombre": "Sableye", "tipos": ["Siniestro", "Fantasma"], "debilidades": ["Hada"], "mega_evolucion": True, "gigamax": False},
    {"numero": 306, "nombre": "Aggron", "tipos": ["Acero", "Roca"], "debilidades": ["Lucha", "Tierra", "Agua"], "mega_evolucion": True, "gigamax": False},
    {"numero": 334, "nombre": "Altaria", "tipos": ["Dragón", "Volador"], "debilidades": ["Hielo", "Dragón", "Hada", "Roca"], "mega_evolucion": True, "gigamax": False},
    {"numero": 376, "nombre": "Metagross", "tipos": ["Acero", "Psíquico"], "debilidades": ["Fuego", "Tierra", "Fantasma", "Siniestro"], "mega_evolucion": True, "gigamax": False},
    {"numero": 384, "nombre": "Rayquaza", "tipos": ["Dragón", "Volador"], "debilidades": ["Hielo", "Dragón", "Hada", "Roca"], "mega_evolucion": True, "gigamax": False},
    
    # Generación 4
    {"numero": 389, "nombre": "Torterra", "tipos": ["Planta", "Tierra"], "debilidades": ["Fuego", "Hielo", "Volador", "Bicho"], "mega_evolucion": False, "gigamax": False},
    {"numero": 392, "nombre": "Infernape", "tipos": ["Fuego", "Lucha"], "debilidades": ["Agua", "Psíquico", "Volador", "Tierra"], "mega_evolucion": False, "gigamax": False},
    {"numero": 395, "nombre": "Empoleon", "tipos": ["Agua", "Acero"], "debilidades": ["Lucha", "Tierra", "Eléctrico"], "mega_evolucion": False, "gigamax": False},
    {"numero": 405, "nombre": "Luxray", "tipos": ["Eléctrico"], "debilidades": ["Tierra"], "mega_evolucion": False, "gigamax": False},
    {"numero": 445, "nombre": "Garchomp", "tipos": ["Dragón", "Tierra"], "debilidades": ["Hielo", "Dragón", "Hada"], "mega_evolucion": True, "gigamax": False},
    {"numero": 448, "nombre": "Lucario", "tipos": ["Lucha", "Acero"], "debilidades": ["Fuego", "Lucha", "Tierra"], "mega_evolucion": True, "gigamax": False},
    {"numero": 460, "nombre": "Abomasnow", "tipos": ["Planta", "Hielo"], "debilidades": ["Fuego", "Lucha", "Veneno", "Volador", "Acero", "Roca", "Bicho"], "mega_evolucion": True, "gigamax": False},
    {"numero": 475, "nombre": "Gallade", "tipos": ["Psíquico", "Lucha"], "debilidades": ["Volador", "Fantasma", "Hada"], "mega_evolucion": True, "gigamax": False},
    
    # Generación 5
    {"numero": 497, "nombre": "Serperior", "tipos": ["Planta"], "debilidades": ["Fuego", "Hielo", "Veneno", "Volador", "Bicho"], "mega_evolucion": False, "gigamax": False},
    {"numero": 500, "nombre": "Emboar", "tipos": ["Fuego", "Lucha"], "debilidades": ["Agua", "Psíquico", "Volador", "Tierra"], "mega_evolucion": False, "gigamax": False},
    {"numero": 503, "nombre": "Samurott", "tipos": ["Agua"], "debilidades": ["Planta", "Eléctrico"], "mega_evolucion": False, "gigamax": False},
    {"numero": 530, "nombre": "Excadrill", "tipos": ["Tierra", "Acero"], "debilidades": ["Fuego", "Agua", "Lucha", "Tierra"], "mega_evolucion": False, "gigamax": False},
    {"numero": 553, "nombre": "Krookodile", "tipos": ["Tierra", "Siniestro"], "debilidades": ["Agua", "Planta", "Hielo", "Lucha", "Bicho", "Hada"], "mega_evolucion": False, "gigamax": False},
    {"numero": 571, "nombre": "Zoroark", "tipos": ["Siniestro"], "debilidades": ["Lucha", "Bicho", "Hada"], "mega_evolucion": False, "gigamax": False},
    {"numero": 609, "nombre": "Chandelure", "tipos": ["Fantasma", "Fuego"], "debilidades": ["Agua", "Tierra", "Roca", "Fantasma", "Siniestro"], "mega_evolucion": False, "gigamax": False},
    {"numero": 635, "nombre": "Hydreigon", "tipos": ["Siniestro", "Dragón"], "debilidades": ["Lucha", "Bicho", "Hielo", "Dragón", "Hada"], "mega_evolucion": False, "gigamax": False},
    
    # Generación 6
    {"numero": 652, "nombre": "Chesnaught", "tipos": ["Planta", "Lucha"], "debilidades": ["Fuego", "Hielo", "Veneno", "Volador", "Psíquico", "Hada"], "mega_evolucion": False, "gigamax": False},
    {"numero": 655, "nombre": "Delphox", "tipos": ["Fuego", "Psíquico"], "debilidades": ["Agua", "Tierra", "Roca", "Fantasma", "Siniestro"], "mega_evolucion": False, "gigamax": False},
    {"numero": 658, "nombre": "Greninja", "tipos": ["Agua", "Siniestro"], "debilidades": ["Planta", "Eléctrico", "Lucha", "Bicho", "Hada"], "mega_evolucion": False, "gigamax": False},
    {"numero": 663, "nombre": "Talonflame", "tipos": ["Fuego", "Volador"], "debilidades": ["Agua", "Eléctrico", "Roca"], "mega_evolucion": False, "gigamax": False},
    {"numero": 700, "nombre": "Sylveon", "tipos": ["Hada"], "debilidades": ["Veneno", "Acero"], "mega_evolucion": False, "gigamax": False},
    {"numero": 706, "nombre": "Goodra", "tipos": ["Dragón"], "debilidades": ["Hielo", "Dragón", "Hada"], "mega_evolucion": False, "gigamax": False},
    {"numero": 715, "nombre": "Noivern", "tipos": ["Volador", "Dragón"], "debilidades": ["Hielo", "Roca", "Dragón", "Hada"], "mega_evolucion": False, "gigamax": False},
    
    # Generación 7
    {"numero": 727, "nombre": "Incineroar", "tipos": ["Fuego", "Siniestro"], "debilidades": ["Agua", "Lucha", "Tierra", "Roca"], "mega_evolucion": False, "gigamax": False},
    {"numero": 730, "nombre": "Primarina", "tipos": ["Agua", "Hada"], "debilidades": ["Planta", "Eléctrico", "Veneno"], "mega_evolucion": False, "gigamax": False},
    {"numero": 738, "nombre": "Vikavolt", "tipos": ["Bicho", "Eléctrico"], "debilidades": ["Fuego", "Roca"], "mega_evolucion": False, "gigamax": False},
    {"numero": 745, "nombre": "Lycanroc", "tipos": ["Roca"], "debilidades": ["Agua", "Planta", "Lucha", "Tierra", "Acero"], "mega_evolucion": False, "gigamax": False},
    {"numero": 758, "nombre": "Salazzle", "tipos": ["Veneno", "Fuego"], "debilidades": ["Agua", "Psíquico", "Tierra", "Roca"], "mega_evolucion": False, "gigamax": False},
    {"numero": 778, "nombre": "Mimikyu", "tipos": ["Fantasma", "Hada"], "debilidades": ["Fantasma", "Acero"], "mega_evolucion": False, "gigamax": False},
    {"numero": 785, "nombre": "Tapu Koko", "tipos": ["Eléctrico", "Hada"], "debilidades": ["Veneno", "Tierra"], "mega_evolucion": False, "gigamax": False},
    {"numero": 791, "nombre": "Solgaleo", "tipos": ["Psíquico", "Acero"], "debilidades": ["Fuego", "Tierra", "Fantasma", "Siniestro"], "mega_evolucion": False, "gigamax": False},
    {"numero": 792, "nombre": "Lunala", "tipos": ["Psíquico", "Fantasma"], "debilidades": ["Fantasma", "Siniestro"], "mega_evolucion": False, "gigamax": False},
    
    # Generación 8
    {"numero": 812, "nombre": "Rillaboom", "tipos": ["Planta"], "debilidades": ["Fuego", "Hielo", "Veneno", "Volador", "Bicho"], "mega_evolucion": False, "gigamax": True},
    {"numero": 815, "nombre": "Cinderace", "tipos": ["Fuego"], "debilidades": ["Agua", "Tierra", "Roca"], "mega_evolucion": False, "gigamax": True},
    {"numero": 818, "nombre": "Inteleon", "tipos": ["Agua"], "debilidades": ["Planta", "Eléctrico"], "mega_evolucion": False, "gigamax": True},
    {"numero": 823, "nombre": "Corviknight", "tipos": ["Volador", "Acero"], "debilidades": ["Fuego", "Eléctrico"], "mega_evolucion": False, "gigamax": True},
    {"numero": 826, "nombre": "Orbeetle", "tipos": ["Bicho", "Psíquico"], "debilidades": ["Fuego", "Volador", "Roca", "Fantasma", "Siniestro"], "mega_evolucion": False, "gigamax": True},
    {"numero": 834, "nombre": "Drednaw", "tipos": ["Agua", "Roca"], "debilidades": ["Planta", "Eléctrico", "Lucha", "Tierra"], "mega_evolucion": False, "gigamax": True},
    {"numero": 839, "nombre": "Coalossal", "tipos": ["Roca", "Fuego"], "debilidades": ["Agua", "Tierra", "Lucha", "Roca"], "mega_evolucion": False, "gigamax": True},
    {"numero": 841, "nombre": "Flapple", "tipos": ["Planta", "Dragón"], "debilidades": ["Hielo", "Veneno", "Volador", "Bicho", "Dragón", "Hada"], "mega_evolucion": False, "gigamax": True},
    {"numero": 842, "nombre": "Appletun", "tipos": ["Planta", "Dragón"], "debilidades": ["Hielo", "Veneno", "Volador", "Bicho", "Dragón", "Hada"], "mega_evolucion": False, "gigamax": True},
    {"numero": 844, "nombre": "Sandaconda", "tipos": ["Tierra"], "debilidades": ["Agua", "Planta", "Hielo"], "mega_evolucion": False, "gigamax": True},
    {"numero": 849, "nombre": "Toxtricity", "tipos": ["Eléctrico", "Veneno"], "debilidades": ["Tierra", "Psíquico"], "mega_evolucion": False, "gigamax": True},
    {"numero": 851, "nombre": "Centiskorch", "tipos": ["Fuego", "Bicho"], "debilidades": ["Agua", "Volador", "Roca"], "mega_evolucion": False, "gigamax": True},
    {"numero": 858, "nombre": "Hatterene", "tipos": ["Psíquico", "Hada"], "debilidades": ["Veneno", "Fantasma", "Acero"], "mega_evolucion": False, "gigamax": True},
    {"numero": 861, "nombre": "Grimmsnarl", "tipos": ["Siniestro", "Hada"], "debilidades": ["Veneno", "Acero", "Hada"], "mega_evolucion": False, "gigamax": True},
    {"numero": 869, "nombre": "Alcremie", "tipos": ["Hada"], "debilidades": ["Veneno", "Acero"], "mega_evolucion": False, "gigamax": True},
    {"numero": 879, "nombre": "Copperajah", "tipos": ["Acero"], "debilidades": ["Fuego", "Lucha", "Tierra"], "mega_evolucion": False, "gigamax": True},
    {"numero": 884, "nombre": "Duraludon", "tipos": ["Acero", "Dragón"], "debilidades": ["Lucha", "Tierra"], "mega_evolucion": False, "gigamax": True},
    {"numero": 887, "nombre": "Dragapult", "tipos": ["Dragón", "Fantasma"], "debilidades": ["Hielo", "Dragón", "Fantasma", "Siniestro", "Hada"], "mega_evolucion": False, "gigamax": False},
    {"numero": 888, "nombre": "Zacian", "tipos": ["Hada"], "debilidades": ["Veneno", "Acero"], "mega_evolucion": False, "gigamax": False},
    {"numero": 889, "nombre": "Zamazenta", "tipos": ["Lucha"], "debilidades": ["Volador", "Psíquico", "Hada"], "mega_evolucion": False, "gigamax": False},
    {"numero": 890, "nombre": "Eternatus", "tipos": ["Veneno", "Dragón"], "debilidades": ["Psíquico", "Tierra", "Hielo", "Dragón"], "mega_evolucion": False, "gigamax": False},
    
    # Generación 9
    {"numero": 908, "nombre": "Meowscarada", "tipos": ["Planta", "Siniestro"], "debilidades": ["Fuego", "Hielo", "Lucha", "Veneno", "Volador", "Bicho", "Hada"], "mega_evolucion": False, "gigamax": False},
    {"numero": 911, "nombre": "Skeledirge", "tipos": ["Fuego", "Fantasma"], "debilidades": ["Agua", "Tierra", "Roca", "Fantasma", "Siniestro"], "mega_evolucion": False, "gigamax": False},
    {"numero": 914, "nombre": "Quaquaval", "tipos": ["Agua", "Lucha"], "debilidades": ["Planta", "Eléctrico", "Volador", "Psíquico", "Hada"], "mega_evolucion": False, "gigamax": False},
    {"numero": 923, "nombre": "Pawmot", "tipos": ["Eléctrico", "Lucha"], "debilidades": ["Tierra", "Psíquico", "Hada"], "mega_evolucion": False, "gigamax": False},
    {"numero": 945, "nombre": "Grafaiai", "tipos": ["Veneno", "Normal"], "debilidades": ["Tierra", "Psíquico"], "mega_evolucion": False, "gigamax": False},
    {"numero": 947, "nombre": "Brambleghast", "tipos": ["Planta", "Fantasma"], "debilidades": ["Fuego", "Hielo", "Volador", "Fantasma", "Siniestro"], "mega_evolucion": False, "gigamax": False},
    {"numero": 952, "nombre": "Scovillain", "tipos": ["Planta", "Fuego"], "debilidades": ["Volador", "Veneno", "Roca"], "mega_evolucion": False, "gigamax": False},
    {"numero": 962, "nombre": "Bombirdier", "tipos": ["Volador", "Siniestro"], "debilidades": ["Eléctrico", "Hielo", "Roca", "Hada"], "mega_evolucion": False, "gigamax": False},
    {"numero": 966, "nombre": "Revavroom", "tipos": ["Acero", "Veneno"], "debilidades": ["Fuego", "Tierra"], "mega_evolucion": False, "gigamax": False},
    {"numero": 972, "nombre": "Houndstone", "tipos": ["Fantasma"], "debilidades": ["Fantasma", "Siniestro"], "mega_evolucion": False, "gigamax": False},
    {"numero": 978, "nombre": "Tatsugiri", "tipos": ["Dragón", "Agua"], "debilidades": ["Dragón", "Hada"], "mega_evolucion": False, "gigamax": False},
    {"numero": 983, "nombre": "Kingambit", "tipos": ["Siniestro", "Acero"], "debilidades": ["Fuego", "Lucha", "Tierra"], "mega_evolucion": False, "gigamax": False},
    {"numero": 987, "nombre": "Flutter Mane", "tipos": ["Fantasma", "Hada"], "debilidades": ["Fantasma", "Acero"], "mega_evolucion": False, "gigamax": False},
    {"numero": 1003, "nombre": "Ting-Lu", "tipos": ["Siniestro", "Tierra"], "debilidades": ["Agua", "Planta", "Hielo", "Lucha", "Bicho", "Hada"], "mega_evolucion": False, "gigamax": False},
    {"numero": 1007, "nombre": "Koraidon", "tipos": ["Lucha", "Dragón"], "debilidades": ["Psíquico", "Volador", "Hielo", "Dragón", "Hada"], "mega_evolucion": False, "gigamax": False},
    {"numero": 1008, "nombre": "Miraidon", "tipos": ["Eléctrico", "Dragón"], "debilidades": ["Tierra", "Hielo", "Dragón", "Hada"], "mega_evolucion": False, "gigamax": False},
]