from List_ import List

class starwars_data:
    @staticmethod
    def get_jedis():
        return List([ {"name": "Aayla Secura", "masters": ["Kit Fisto"], "lightsaber_colors": ["Blue"], "species": "Twi'lek", "padawans": None},
    {"name": "Adi Gallia", "masters": ["Sifo-Dyas"], "lightsaber_colors": ["Green"], "species": "Tholothian", "padawans": None},
    {"name": "Anakin Skywalker", "masters": ["Obi-Wan Kenobi"], "lightsaber_colors": ["Blue"], "species": "Human", "padawans": ["Ahsoka Tano"]},
    {"name": "Ahsoka Tano", "masters": ["Anakin Skywalker"], "lightsaber_colors": ["Green", "White"], "species": "Togruta", "padawans": None},
    {"name": "Barriss Offee", "masters": ["Luminara Unduli"], "lightsaber_colors": ["Blue"], "species": "Mirialan", "padawans": None},
    {"name": "Ben Skywalker", "masters": ["Luke Skywalker"], "lightsaber_colors": ["Green"], "species": "Human", "padawans": None},
    {"name": "Coleman Kcaj", "masters": ["Jocasta Nu"], "lightsaber_colors": ["Blue"], "species": "Human", "padawans": None},
    {"name": "Count Dooku", "masters": ["Yoda"], "lightsaber_colors": ["Red"], "species": "Human", "padawans": ["Qui-Gon Jinn"]},
    {"name": "Depa Billaba", "masters": ["Thame Cerulian"], "lightsaber_colors": ["Blue"], "species": "Human", "padawans": ["Kanan Jarrus"]},
    {"name": "Eeth Koth", "masters": ["Sifo-Dyas"], "lightsaber_colors": ["Green"], "species": "Zabrak", "padawans": None},
    {"name": "Even Piell", "masters": ["Thame Cerulian"], "lightsaber_colors": ["Green"], "species": "Malevolence", "padawans": None},
    {"name": "Exar Kun", "masters": None, "lightsaber_colors": ["Red", "Blue"], "species": "Human", "padawans": None},
    {"name": "Ezra Bridger", "masters": ["Kanan Jarrus"], "lightsaber_colors": ["Green"], "species": "Human", "padawans": None},
    {"name": "Finn", "masters": None, "lightsaber_colors": ["Blue"], "species": "Human", "padawans": None},
    {"name": "Garrick Versio", "masters": ["Shaak Ti"], "lightsaber_colors": ["Blue"], "species": "Human", "padawans": None},
    {"name": "Yoda", "masters": None, "lightsaber_colors": ["Green"], "species": "Yoda's species", "padawans": ["Luke Skywalker", "Count Dooku"]},
    {"name": "Huyang", "masters": None, "lightsaber_colors": ["Yellow"], "species": "Droid", "padawans": None},
    {"name": "Jocasta Nu", "masters": None, "lightsaber_colors": ["Blue"], "species": "Human", "padawans": ["Coleman Kcaj"]},
    {"name": "Kanan Jarrus", "masters": ["Depa Billaba"], "lightsaber_colors": ["Green"], "species": "Human", "padawans": ["Ezra Bridger"]},
    {"name": "Kit Fisto", "masters": ["K'Kruhk"], "lightsaber_colors": ["Green"], "species": "Nautolan", "padawans": ["Aayla Secura"]},
    {"name": "Ki-Adi-Mundi", "masters": ["Dooku"], "lightsaber_colors": ["Blue"], "species": "Cerean", "padawans": None},
    {"name": "Luminara Unduli", "masters": ["K'Kruhk"], "lightsaber_colors": ["Green"], "species": "Mirialan", "padawans": ["Barriss Offee"]},
    {"name": "Luke Skywalker", "masters": ["Obi-Wan Kenobi", "Yoda"], "lightsaber_colors": ["Green", "Blue"], "species": "Human", "padawans": ["Ben Skywalker"]},
    {"name": "Mace Windu", "masters": ["Thame Cerulian"], "lightsaber_colors": ["Purple"], "species": "Human", "padawans": None},
    {"name": "Obi-Wan Kenobi", "masters": ["Qui-Gon Jinn"], "lightsaber_colors": ["Blue"], "species": "Human", "padawans": ["Anakin Skywalker"]},
    {"name": "Plo Koon", "masters": ["Tyvokka"], "lightsaber_colors": ["Blue"], "species": "Kel Dor", "padawans": None},
    {"name": "Qui-Gon Jinn", "masters": ["Count Dooku"], "lightsaber_colors": ["Green"], "species": "Human", "padawans": ["Obi-Wan Kenobi"]},
    {"name": "Saesee Tiin", "masters": ["Cin Drallig"], "lightsaber_colors": ["Green"], "species": "Iktotchi", "padawans": None},
    {"name": "Shaak Ti", "masters": ["Tsui Choi"], "lightsaber_colors": ["Red"], "species": "Togruta", "padawans": ["Garrick Versio"]},
    {"name": "Satele Shan", "masters": ["Tavian"], "lightsaber_colors": ["Blue"], "species": "Human", "padawans": None},
    {"name": "Tahl", "masters": ["Dendup"], "lightsaber_colors": ["Blue"], "species": "Human", "padawans": None},
    {"name": "Ulic Qel-Droma", "masters": ["Cinnagar"], "lightsaber_colors": ["Red"], "species": "Human", "padawans": None},
    {"name": "Ventress", "masters": ["Count Dooku"], "lightsaber_colors": ["Red"], "species": "Dathomirian", "padawans": None},
    {"name": "Wilhuff Tarkin", "masters": None, "lightsaber_colors": None, "species": "Human", "padawans": None},
    {"name": "Agen Kolar", "masters": ["Mace Windu"], "lightsaber_colors": ["Yellow"], "species": "Human", "padawans": None},
    {"name": "Coleman Trebor", "masters": ["Yoda"], "lightsaber_colors": ["Green"], "species": "Vurk", "padawans": None},
    {"name": "Adi Gallia", "masters": ["Sifo-Dyas"], "lightsaber_colors": ["Green"], "species": "Tholothian", "padawans": None},
    {"name": "An'ya Kuro", "masters": ["Var Suth"], "lightsaber_colors": ["Blue"], "species": "Human", "padawans": None},
    {"name": "Agen Kolar", "masters": ["Mace Windu"], "lightsaber_colors": ["Yellow"], "species": "Human", "padawans": None},
    {"name": "Bultar Swan", "masters": ["Obi-Wan Kenobi"], "lightsaber_colors": ["Blue"], "species": "Human", "padawans": None},
    {"name": "Cin Drallig", "masters": ["Mace Windu"], "lightsaber_colors": ["Blue"], "species": "Human", "padawans": ["Saesee Tiin"]},
    {"name": "Depa Billaba", "masters": ["Thame Cerulian"], "lightsaber_colors": ["Blue"], "species": "Human", "padawans": ["Kanan Jarrus"]},
    {"name": "Eeth Koth", "masters": ["Sifo-Dyas"], "lightsaber_colors": ["Green"], "species": "Zabrak", "padawans": None},
    {"name": "Kit Fisto", "masters": ["K'Kruhk"], "lightsaber_colors": ["Green"], "species": "Nautolan", "padawans": ["Aayla Secura"]},
])