from List_ import List

class SuperheroesData:
    @staticmethod
    def get_superheroes():
        return List([
            { "name": "Hal Jordan", "alias": "Green Lantern", "first_appearance": 1959, "is_villain": False, "publisher": "DC",
              "short_bio": "A test pilot chosen to wield the power ring of the Green Lantern Corps, protecting the universe." },
            { "name": "Nathaniel Richards", "alias": "Kang the Conqueror", "first_appearance": 1964, "is_villain": True, "publisher": "Marvel",
              "short_bio": "A time-traveling warlord who battles heroes across different timelines." },
            { "name": "Bruce Banner", "alias": "Hulk", "first_appearance": 1962, "is_villain": False, "publisher": "Marvel",
              "short_bio": "A scientist who transforms into a green-skinned giant when enraged." },
            { "name": "Natasha Romanoff", "alias": "Black Widow", "first_appearance": 1964, "is_villain": False, "publisher": "Marvel",
              "short_bio": "A highly trained spy and expert martial artist." },
            { "name": "Felicia Hardy", "alias": "Black Cat", "first_appearance": 1979, "is_villain": True, "publisher": "Marvel",
              "short_bio": "A skilled burglar with bad luck powers, often in the gray area between hero and villain." },
            { "name": "Tony Stark", "alias": "Iron Man", "first_appearance": 1963, "is_villain": False, "publisher": "Marvel",
              "short_bio": "A genius inventor and billionaire who built a suit of armor to become Iron Man." },
            { "name": "Max Eisenhardt", "alias": "Magneto", "first_appearance": 1963, "is_villain": True, "publisher": "Marvel",
              "short_bio": "A powerful mutant controlling magnetic fields, often opposing the X-Men." },
            { "name": "Ororo Munroe", "alias": "Storm", "first_appearance": 1975, "is_villain": False, "publisher": "Marvel",
              "short_bio": "A mutant who can control the weather and a leader of the X-Men." },
            { "name": "Eddie Brock", "alias": "Venom", "first_appearance": 1988, "is_villain": True, "publisher": "Marvel",
              "short_bio": "A journalist bonded with an alien symbiote, becoming the anti-hero Venom." },
            { "name": "Wanda Maximoff", "alias": "Scarlet Witch", "first_appearance": 1964, "is_villain": False, "publisher": "Marvel",
              "short_bio": "A mutant with chaos magic, capable of altering reality." },
            { "name": "Emil Blonsky", "alias": "Abomination", "first_appearance": 1967, "is_villain": True, "publisher": "Marvel",
              "short_bio": "A former KGB agent who transformed into a gamma-powered monster." },
            { "name": "Adam Warlock", "alias": "Adam Warlock", "first_appearance": 1967, "is_villain": False, "publisher": "Marvel",
              "short_bio": "A perfect artificial human and cosmic protector, wielder of the Soul Gem." },
            { "name": "Warren Worthington III", "alias": "Angel", "first_appearance": 1963, "is_villain": False, "publisher": "Marvel",
              "short_bio": "A founding X-Men member with large feathered wings that allow him to fly." },
            { "name": "Annihilus", "alias": "Annihilus", "first_appearance": 1968, "is_villain": True, "publisher": "Marvel",
              "short_bio": "Ruler of the Negative Zone with insectoid powers, obsessed with immortality." },
            { "name": "Hank Pym", "alias": "Ant Man", "first_appearance": 1962, "is_villain": False, "publisher": "Marvel",
              "short_bio": "Scientist who discovered Pym Particles, allowing him to shrink and grow in size." },
            { "name": "En Sabah Nur", "alias": "Apocalypse", "first_appearance": 1986, "is_villain": True, "publisher": "Marvel",
              "short_bio": "An ancient mutant with enhanced abilities and a philosophy of survival of the fittest." },
            { "name": "Helmut Zemo", "alias": "Baron Zemo", "first_appearance": 1973, "is_villain": True, "publisher": "Marvel",
              "short_bio": "A brilliant strategist and adversary of Captain America." },
            { "name": "Wade Wilson", "alias": "Deadpool", "first_appearance": 1991, "is_villain": False, "publisher": "Marvel",
              "short_bio": "A mercenary with a healing factor and a penchant for breaking the fourth wall." },
            { "name": "Peter Parker", "alias": "Spider-Man", "first_appearance": 1962, "is_villain": False, "publisher": "Marvel",
              "short_bio": "A teenager bitten by a radioactive spider, gaining spider-like abilities." },
            { "name": "Norman Osborn", "alias": "Green Goblin", "first_appearance": 1964, "is_villain": True, "publisher": "Marvel",
              "short_bio": "A wealthy industrialist who becomes the insane Green Goblin." },
            { "name": "Steve Rogers", "alias": "Captain America", "first_appearance": 1941, "is_villain": False, "publisher": "Marvel",
              "short_bio": "A super-soldier from World War II and a symbol of heroism." },
            { "name": "James Buchanan Barnes", "alias": "Winter Soldier", "first_appearance": 1941, "is_villain": True, "publisher": "Marvel",
              "short_bio": "Brainwashed assassin and former ally of Captain America." },
            { "name": "Clint Barton", "alias": "Hawkeye", "first_appearance": 1964, "is_villain": False, "publisher": "Marvel",
              "short_bio": "Master archer and member of the Avengers." },
            { "name": "Stephen Strange", "alias": "Doctor Strange", "first_appearance": 1963, "is_villain": False, "publisher": "DC",
              "short_bio": "Former surgeon turned Sorcerer Supreme, protecting Earth from magical threats." },
            { "name": "Victor Von Doom", "alias": "Doctor Doom", "first_appearance": 1962, "is_villain": True, "publisher": "Marvel",
              "short_bio": "Ruler of Latveria and a brilliant sorcerer-scientist." },
            { "name": "Reed Richards", "alias": "Mr. Fantastic", "first_appearance": 1961, "is_villain": False, "publisher": "Marvel",
              "short_bio": "Leader of the Fantastic Four with elastic body and genius intellect." },
            { "name": "Susan Storm", "alias": "Invisible Woman", "first_appearance": 1961, "is_villain": False, "publisher": "Marvel",
              "short_bio": "Member of the Fantastic Four with invisibility and force field powers." },
            { "name": "Johnny Storm", "alias": "Human Torch", "first_appearance": 1961, "is_villain": False, "publisher": "Marvel",
              "short_bio": "A member of the Fantastic Four who can ignite his body in flames." },
            { "name": "Ben Grimm", "alias": "The Thing", "first_appearance": 1961, "is_villain": False, "publisher": "Marvel",
              "short_bio": "A rocky-skinned powerhouse and loyal member of the Fantastic Four." },
            { "name": "Charles Xavier", "alias": "Professor X", "first_appearance": 1963, "is_villain": False, "publisher": "Marvel",
              "short_bio": "Founder of the X-Men and a powerful telepath." },
            { "name": "Jean Grey", "alias": "Phoenix", "first_appearance": 1963, "is_villain": False, "publisher": "Marvel",
              "short_bio": "Mutant with powerful telepathy and host of the Phoenix Force." },
            { "name": "Scott Summers", "alias": "Cyclops", "first_appearance": 1963, "is_villain": False, "publisher": "Marvel",
              "short_bio": "Emits optic blasts and leads the X-Men." },
            { "name": "Logan", "alias": "Wolverine", "first_appearance": 1974, "is_villain": False, "publisher": "Marvel",
              "short_bio": "Mutant with healing factor, animal-like senses, and adamantium claws." },
            { "name": "Remy LeBeau", "alias": "Gambit", "first_appearance": 1990, "is_villain": False, "publisher": "Marvel",
              "short_bio": "Mutant who charges objects with kinetic energy, often a thief and hero." },
            { "name": "Anna Marie", "alias": "Rogue", "first_appearance": 1981, "is_villain": False, "publisher": "Marvel",
              "short_bio": "Mutant who absorbs powers and memories through touch." },
            { "name": "Piotr Rasputin", "alias": "Colossus", "first_appearance": 1975, "is_villain": False, "publisher": "Marvel",
              "short_bio": "Mutant who can transform his body into organic steel." },
            { "name": "Kurt Wagner", "alias": "Nightcrawler", "first_appearance": 1975, "is_villain": False, "publisher": "Marvel",
              "short_bio": "Blue-skinned mutant with teleportation abilities and acrobatics." },
            { "name": "Carol Danvers", "alias": "Captain Marvel", "first_appearance": 1968, "is_villain": False, "publisher": "Marvel",
              "short_bio": "A former Air Force pilot empowered with cosmic abilities, fighting as a superhero in the Marvel universe." },
            { "name": "Diana Prince", "alias": "Wonder Woman", "first_appearance": 1941, "is_villain": False, "publisher": "DC",
              "short_bio": "An Amazonian princess with superhuman strength, agility, and a mission to bring peace and justice to the world." },
            { "name": "Barry Allen", "alias": "Flash", "first_appearance": 1956, "is_villain": False, "publisher": "DC",
             "short_bio": "A forensic scientist who gains super-speed abilities and fights crime as the Scarlet Speedster, protecting Central City." }

 ])

